### ISSUE TITLE
Market Orders & Limit Orders Dev - swap()

### ISSUE THREAD

**Issue by shakeib98** [decaswap-labs/core#27]
``` 
function swapMarketOrder(...., isMarketOrder) external {}
```
``` 
function swapLimitOrder(...., isMarketOrder) external {}
```

## Flow and Details (Market Order):
- create a function to execute market orders
- market orders will be executed at the currentPrice of the pool
- During the execution of market orders, they will be setllted against the opp queue (orders which are at the highest price marker of the opp direction)
- If there's no oppQueue present at the highest price marker, then PRICE_PRECISION will be subtracted to obtain the next key
- Order will be settled against that ONE swap or MULTIPLE swaps of opp direction
- If order is still remained, one stream will be handled against the pool
- If order is still remained, order will be pushed into the array of orderBook with isMarketOrder uint8 val = 1

## Flow and Details (Limit Order):
- create a function to execute limit orders
- market orders will be executed at the executionPrice of the swap
- During the execution of market orders, they will be setllted against the opp queue (Orders which are at the same price as the executionPrice of the swap)
- If there's no oppQueue present at the key price marker, then move onto the pool settling.
- If order is still remained, one stream will be handled against the pool (if the currentPoolPrice >= executionPrice {of swap})
- If order is still remained, order will be pushed into the array of orderBook with isMarketOrder uint8 val = 2

**Comment by immaxkent** [comment]
*Flow and Details (Trigger Order):*

- both market and trigger orders go in here
- include the marketOrderBook `mapping(pairdId => Swaps[])`
- be sure to include uint8 isMarketOrder values to the swap structs
- include the logic to evaluate if a trigger order can be converted to market order. If yes, stream in the usual process
